openapi: 3.0.0
info:
  title: Olevegic Addon
  version: 1.0.0
  description: Documentation for Addon REST API
paths:
  /:
    get:
      summary: Redirect to the application descriptor file
      description: Redirects to `/atlassian-connect.json`.
      responses:
        302:
          description: Redirection
  /todolist:
    get:
      summary: Display the TodoList page
      description: Returns the TodoList page for authorized users.
      security:
        - jwtAuth: []
      responses:
        200:
          description: TodoList page
        401:
          description: Authentication required
  /api/projects:
    get:
      summary: Retrieve the list of Jira projects
      description: Returns a list of Jira projects available to the current user.
      tags:
        - Projects
      security:
        - jwtAuth: []
      responses:
        200:
          description: Successful response with an array of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
        401:
          description: Authentication required
  /api/task:
    post:
      summary: Retrieve the list of tasks from Jira
      description: Returns a list of Jira tasks matching the given JQL query.
      tags:
        - Tasks
      security:
        - jwtAuth: []
      requestBody:
        description: Request parameters for Jira (formatted using formQuery)
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jql:
                  type: string
                  description: JQL query for task filtering
                  example: project = "My Project" AND status = "In Progress"
                maxResults:
                  type: integer
                  description: Maximum number of tasks to return
                  example: 50
                startAt:
                  type: integer
                  description: Index of the first task to return (for pagination)
                  example: 0
      responses:
        200:
          description: Successful response with an array of tasks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        400:
          description: Invalid request (e.g., incorrect JQL)
        401:
          description: Authentication required
  /api/task/count:
    post:
      summary: Retrieve approximate task count in Jira
      description: Returns an approximate count of Jira tasks matching the given JQL query.
      tags:
        - Tasks
      security:
        - jwtAuth: []
      requestBody:
        description: Jira project key
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                  description: Jira project key
                  example: "MYPROJECT"
      responses:
        200:
          description: Successful response with approximate task count
        400:
          description: Invalid request (e.g., incorrect project key)
        401:
          description: Authentication required
  /api/task/delete:
    post:
      summary: Delete a Jira task by ID
      description: Deletes a specific Jira task based on the provided issue ID.
      tags:
        - Tasks
      security:
        - jwtAuth: []
      requestBody:
        description: Jira issue ID
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                issueID:
                  type: string
                  description: Jira issue ID
                  example: "10001"
      responses:
        200:
          description: Task deleted successfully
        400:
          description: Invalid request (e.g., missing issue ID)
        401:
          description: Authentication required
        403:
          description: Forbidden - Insufficient permissions to delete the issue
        500:
          description: Internal server error during deletion
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          description: Task ID
        key:
          type: string
          description: Task key
        summary:
          type: string
          description: Task summary
        assignee:
          type: object
          description: Task assignee (can be null)
        status:
          type: object
          description: Task status
          properties:
            self:
              type: string
              description: Status resource URL
            description:
              type: string
              description: Status description
            iconUrl:
              type: string
              description: Status icon URL
            name:
              type: string
              description: Status name
            id:
              type: string
              description: Status ID
            statusCategory:
              type: object
              description: Status category
    Project:
      type: object
      properties:
        id:
          type: string
          description: Project ID
        key:
          type: string
          description: Project key
        name:
          type: string
          description: Project name
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
